<?php
require_once __DIR__ . '/config.php';
function one_row(string $sql): ?array { try { $r=db()->query($sql); return $r ? ($r->fetch_assoc() ?: null) : null; } catch(Throwable $e){ return null; } }
function many_rows(string $sql): array { try { $r=db()->query($sql); return $r ? $r->fetch_all(MYSQLI_ASSOC) : []; } catch(Throwable $e){ return []; } }
function money($n): string { $v=(float)$n; return $v>0 ? 'Rs. '.number_format($v,0) : 'Free'; }
$id=max(0,(int)($_GET['id'] ?? 0));
$course=one_row("SELECT c.*,COALESCE(cat.name,c.category,'Course') category_name,COALESCE(u.full_name,'Instructor') instructor_name FROM instructor_courses c LEFT JOIN course_categories cat ON cat.id=c.category_id LEFT JOIN users u ON u.id=c.instructor_id WHERE c.id={$id} AND c.status='published' LIMIT 1");
if(!$course){ http_response_code(404); }
$items=$course ? many_rows("SELECT id,content_title,content_type,resource_url,duration_minutes,is_preview,instructions FROM instructor_course_contents WHERE course_id={$id} AND status='published' ORDER BY sort_order ASC,id ASC") : [];
$pageTitle=($course['title'] ?? 'Course').' - '.app_name();
$thumb=trim((string)($course['thumbnail_path'] ?? ''));
$hasThumb=$thumb!=='' && is_file(__DIR__.'/'.ltrim($thumb,'/'));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= h($pageTitle); ?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>
:root{--nav:#07111f;--bg:#f3f8fd;--line:#d9e4ef;--ink:#07111f;--muted:#64748b;--blue:#155dfc;--yellow:#ffdf3b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Poppins,Arial,sans-serif}a{text-decoration:none;color:inherit}.wrap{width:min(1180px,94%);margin:auto}.top{background:var(--nav)}.topin{height:64px;display:flex;align-items:center;justify-content:space-between}.logo img{height:52px}.nav{display:flex;gap:20px;color:#eaf2ff;font-size:13px;font-weight:600}.hero{padding:28px 0}.heroBox{display:grid;grid-template-columns:1fr 360px;gap:22px;align-items:stretch}.panel{background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:0 14px 32px rgba(15,23,42,.06)}.intro{padding:24px}.tag{display:inline-flex;padding:6px 10px;border-radius:999px;background:#eef6ff;color:#155dfc;font-size:11px;font-weight:700}.intro h1{margin:14px 0 10px;font-size:34px;line-height:1.14}.intro p{margin:0;color:#475569;font-size:14px;line-height:1.65}.meta{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.meta span{padding:8px 10px;border-radius:10px;background:#f6faff;border:1px solid #e2edf8;font-size:12px;color:#475569}.side{padding:14px}.thumb{height:190px;border-radius:14px;background:linear-gradient(135deg,#155dfc,#0f766e);display:grid;place-items:center;color:#fff;font-size:38px;font-weight:800;overflow:hidden}.thumb img{width:100%;height:100%;object-fit:cover}.price{display:flex;align-items:center;justify-content:space-between;margin-top:14px;font-size:13px}.price b{font-size:24px}.price del{color:#94a3b8}.cta{margin-top:12px;height:44px;border-radius:10px;background:var(--yellow);display:grid;place-items:center;font-weight:800}.section{padding:0 0 30px}.section h2{font-size:24px;margin:0 0 14px}.curriculum{display:grid;gap:10px}.lesson{display:grid;grid-template-columns:42px 1fr auto;gap:12px;align-items:center;padding:13px 14px;background:#fff;border:1px solid var(--line);border-radius:12px}.num{width:34px;height:34px;border-radius:10px;background:#eef6ff;color:#155dfc;display:grid;place-items:center;font-weight:800;font-size:12px}.lesson h3{margin:0;font-size:14px}.lesson p{margin:3px 0 0;color:#64748b;font-size:12px}.badge{font-size:11px;color:#475569;background:#f1f5f9;border-radius:999px;padding:5px 8px}.empty{padding:24px;text-align:center;color:#64748b}.footer{background:#07111f;color:#cbd5e1;padding:20px 0;text-align:center;font-size:12px}@media(max-width:760px){.nav{display:none}.topin{height:58px;justify-content:center}.logo img{height:44px}.hero{padding:16px 0}.heroBox{grid-template-columns:1fr}.intro{padding:18px}.intro h1{font-size:25px}.side{order:-1}.thumb{height:160px}.lesson{grid-template-columns:36px 1fr}.badge{grid-column:2}.footer{display:none}}
</style></head><body><header class="top"><div class="wrap topin"><a class="logo" href="<?= h(app_url('index')); ?>"><img src="<?= h(app_url('assets/grlogo.png')); ?>" alt="GYAN NEXA"></a><nav class="nav"><a href="<?= h(app_url('index')); ?>">Home</a><a href="<?= h(app_url('gov-exam-tests')); ?>">Mock Tests</a><a href="<?= h(app_url('login')); ?>">Login</a></nav></div></header><?php if(!$course): ?><main class="wrap hero"><div class="panel empty">Course not found.</div></main><?php else: ?><main><section class="wrap hero"><div class="heroBox"><div class="panel intro"><span class="tag"><?= h($course['category_name']); ?></span><h1><?= h($course['title']); ?></h1><p><?= h($course['short_description'] ?: 'Structured course with organized chapters and practice support.'); ?></p><div class="meta"><span><?= h(ucfirst((string)$course['course_language'])); ?> Medium</span><span><?= h(ucfirst((string)$course['course_level'])); ?> Level</span><span><?= h($course['instructor_name']); ?></span><span><?= h((string)count($items)); ?> Lessons</span></div></div><aside class="panel side"><div class="thumb"><?php if($hasThumb): ?><img src="<?= h(app_url($thumb)); ?>" alt="<?= h($course['title']); ?>"><?php else: ?>GN<?php endif; ?></div><div class="price"><span><?php if((float)$course['original_price']>(float)$course['price']): ?><del><?= h(money($course['original_price'])); ?></del><?php endif; ?></span><b><?= h(money($course['price'])); ?></b></div><a class="cta" href="#curriculum">View Curriculum</a></aside></div></section><section class="wrap section" id="curriculum"><h2>Course Curriculum</h2><div class="curriculum"><?php foreach($items as $i=>$it): ?><article class="lesson"><span class="num"><?= h((string)($i+1)); ?></span><div><h3><?= h($it['content_title']); ?></h3><p><?= h(ucwords(str_replace('_',' ',(string)$it['content_type']))); ?><?= (int)$it['duration_minutes']>0 ? ' - '.h((string)$it['duration_minutes']).' min' : ''; ?></p></div><span class="badge"><?= ((int)$it['is_preview']===1) ? 'Preview' : 'Lesson'; ?></span></article><?php endforeach; ?><?php if(!$items): ?><div class="panel empty">Curriculum will be available soon.</div><?php endif; ?></div></section></main><?php endif; ?><footer class="footer"><div class="wrap">GYAN NEXA Copyright <?= h(date('Y')); ?>. All rights reserved.</div></footer></body></html>