<?php
require_once __DIR__ . '/config.php';
function r1(string $sql): ?array { try { $r=db()->query($sql); return $r ? ($r->fetch_assoc() ?: null) : null; } catch(Throwable $e){ return null; } }
function ra(string $sql): array { try { $r=db()->query($sql); return $r ? $r->fetch_all(MYSQLI_ASSOC) : []; } catch(Throwable $e){ return []; } }
function logo_for(?string $slug,string $name=''): string { $slug=trim((string)$slug); if($slug==='') $slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name),'-')); foreach(['svg','png','jpg','jpeg','webp'] as $ext){$rel='uploads/exam-logos/'.$slug.'.'.$ext; if(is_file(__DIR__.'/'.$rel)) return app_url($rel);} return ''; }
$id=max(0,(int)($_GET['id'] ?? 0));
$mock=r1("SELECT m.*,c.name category_name,c.slug category_slug,s.name subcategory_name,s.slug subcategory_slug FROM gov_exam_mock_tests m LEFT JOIN gov_exam_categories c ON c.id=m.category_id LEFT JOIN gov_exam_categories s ON s.id=m.subcategory_id WHERE m.id={$id} AND m.status='published' LIMIT 1");
if(!$mock){ http_response_code(404); }
$questions=$mock ? ra("SELECT id,question_en,question_hi,option_a_en,option_b_en,option_c_en,option_d_en,option_e_en,correct_answer,marks,negative_marks,explanation_en,sort_order FROM gov_exam_mock_questions WHERE mock_test_id={$id} AND status='active' ORDER BY sort_order ASC,id ASC LIMIT 100") : [];
$total=count($questions); $cat=$mock ? (($mock['subcategory_name'] ?? '') ?: ($mock['category_name'] ?? 'Exam')) : 'Exam'; $logo=$mock ? (logo_for($mock['subcategory_slug'] ?? '',$cat) ?: logo_for($mock['category_slug'] ?? '',$mock['category_name'] ?? '')) : '';
$pageTitle=($mock['title'] ?? 'Mock Test').' - '.app_name();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= h($pageTitle); ?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>
:root{--nav:#07111f;--bg:#f3f8fd;--line:#d9e4ef;--ink:#07111f;--muted:#64748b;--blue:#155dfc;--yellow:#ffdf3b;--green:#00a63e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Poppins,Arial,sans-serif}a{text-decoration:none;color:inherit}.wrap{width:min(1180px,94%);margin:auto}.top{background:var(--nav)}.topin{height:64px;display:flex;align-items:center;justify-content:space-between}.logo img{height:52px}.nav{display:flex;gap:20px;color:#eaf2ff;font-size:13px;font-weight:600}.hero{padding:28px 0 18px}.heroBox{display:grid;grid-template-columns:1fr 300px;gap:18px}.panel{background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:0 14px 32px rgba(15,23,42,.06)}.intro{padding:22px}.introTop{display:flex;align-items:center;gap:12px}.seal{width:48px;height:48px;border-radius:14px;border:1px solid #d7e5f4;background:#fff;display:grid;place-items:center;color:#155dfc;font-weight:800;overflow:hidden}.seal img{width:100%;height:100%;object-fit:contain;padding:4px}.tag{padding:6px 10px;border-radius:999px;background:#eef6ff;color:#155dfc;font-size:11px;font-weight:700}.intro h1{margin:16px 0 10px;font-size:32px;line-height:1.15}.intro p{margin:0;color:#475569;font-size:14px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.stats span{padding:12px;border-radius:12px;background:#f8fbff;border:1px solid #e2edf8;color:#64748b;font-size:12px}.stats b{display:block;color:#07111f;font-size:18px}.side{padding:16px}.side h3{margin:0 0 12px;font-size:16px}.start{height:44px;border-radius:10px;background:var(--yellow);display:grid;place-items:center;font-weight:800;margin-top:14px}.section{padding:0 0 32px}.section h2{margin:0 0 14px;font-size:24px}.qList{display:grid;gap:12px}.detailGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.start.inline{display:inline-grid;width:max-content;padding:0 18px;margin-top:12px}.q{padding:16px;background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:0 10px 24px rgba(15,23,42,.045)}.q h3{margin:0 0 12px;font-size:14px;line-height:1.5}.opts{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.opt{padding:9px 10px;border:1px solid #e2e8f0;border-radius:10px;color:#334155;font-size:12px}.opt.ok{border-color:#86efac;background:#f0fdf4;color:#166534;font-weight:700}.answer{margin-top:10px;color:#166534;font-size:12px;font-weight:700}.empty{padding:24px;text-align:center;color:#64748b}.footer{background:#07111f;color:#cbd5e1;padding:20px 0;text-align:center;font-size:12px}@media(max-width:760px){.nav{display:none}.topin{height:58px;justify-content:center}.logo img{height:44px}.hero{padding:16px 0}.heroBox{grid-template-columns:1fr}.intro{padding:16px}.intro h1{font-size:23px}.stats{grid-template-columns:repeat(3,1fr);gap:8px}.stats span{padding:9px;font-size:10px}.stats b{font-size:15px}.opts{grid-template-columns:1fr}.detailGrid{grid-template-columns:1fr}.q{padding:13px}.footer{display:none}}
</style></head><body><header class="top"><div class="wrap topin"><a class="logo" href="<?= h(app_url('index')); ?>"><img src="<?= h(app_url('assets/grlogo.png')); ?>" alt="GYAN NEXA"></a><nav class="nav"><a href="<?= h(app_url('index')); ?>">Home</a><a href="<?= h(app_url('gov-exam-tests')); ?>">All Mock Tests</a><a href="<?= h(app_url('login')); ?>">Login</a></nav></div></header><?php if(!$mock): ?><main class="wrap hero"><div class="panel empty">Mock test not found.</div></main><?php else: ?><main><section class="wrap hero"><div class="heroBox"><div class="panel intro"><div class="introTop"><span class="seal"><?php if($logo): ?><img src="<?= h($logo); ?>" alt="<?= h($cat); ?>"><?php else: ?><?= h(substr($cat,0,2)); ?><?php endif; ?></span><span class="tag"><?= h($cat); ?></span></div><h1><?= h($mock['title']); ?></h1><p><?= h($mock['description'] ?: 'Practice questions with answer key for focused preparation.'); ?></p><div class="stats"><span><b><?= h((string)$total); ?></b>Questions</span><span><b><?= h((string)((int)$mock['duration_minutes'] ?: 60)); ?></b>Minutes</span><span><b><?= h((string)((float)$mock['total_marks'] ?: $total)); ?></b>Marks</span></div></div><aside class="panel side"><h3>Test Series Summary</h3><p>Full questions and answer key are available after student login.</p><a class="start" href="<?= h(app_url('login')); ?>">Login to Start Test</a></aside></div></section><section class="wrap section" id="questions"><h2>Test Series Details</h2><div class="detailGrid"><article class="q"><h3>What you will get</h3><div class="opts"><div class="opt">Full mock test questions after login</div><div class="opt">Auto score and performance report</div><div class="opt">Answer key after test submission</div><div class="opt">Hindi/English practice support where available</div></div></article><article class="q"><h3>Access required</h3><p>Questions aur answers public page par visible nahi hain. Test attempt karne ke liye student account se login karein.</p><a class="start inline" href="<?= h(app_url('login')); ?>">Login to Start Test</a></article></div></section></main><?php endif; ?><footer class="footer"><div class="wrap">GYAN NEXA Copyright <?= h(date('Y')); ?>. All rights reserved.</div></footer></body></html>