<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../ins/includes/functions.php';

$user = require_login('superadmin');
ensure_instructor_erp_tables();

$pageTitle = 'Chapters';
$pageSubtitle = 'All course chapters and content items generated by instructors.';
$activePage = 'chapters';

$perPageOptions = [10, 25, 50];
$perPage = (int) ($_GET['per_page'] ?? 10);
if (!in_array($perPage, $perPageOptions, true)) {
    $perPage = 10;
}
$page = max(1, (int) ($_GET['page'] ?? 1));
$summary = db()->query("
    SELECT COUNT(*) total,
           SUM(cc.status = 'published') published,
           SUM(cc.status <> 'published') draft,
           COUNT(DISTINCT cc.course_id) courses
    FROM instructor_course_contents cc
")->fetch_assoc() ?: [];
$totalRows = (int) ($summary['total'] ?? 0);
$publishedRows = (int) ($summary['published'] ?? 0);
$draftRows = (int) ($summary['draft'] ?? 0);
$courseRows = (int) ($summary['courses'] ?? 0);
$totalPages = max(1, (int) ceil($totalRows / $perPage));
if ($page > $totalPages) {
    $page = $totalPages;
}
$offset = ($page - 1) * $perPage;

$chapterStmt = db()->prepare("
    SELECT cc.id,
           cc.content_title,
           cc.content_type,
           cc.duration_minutes,
           cc.sort_order,
           cc.status,
           c.title AS course_title,
           u.full_name AS instructor_name,
           c.id AS course_id
    FROM instructor_course_contents cc
    INNER JOIN instructor_courses c ON c.id = cc.course_id
    LEFT JOIN users u ON u.id = cc.instructor_id
    ORDER BY c.title ASC, cc.sort_order ASC
    LIMIT ? OFFSET ?
");
$chapterStmt->bind_param('ii', $perPage, $offset);
$chapterStmt->execute();
$chapters = $chapterStmt->get_result()->fetch_all(MYSQLI_ASSOC);
$pageStart = $totalRows > 0 ? $offset + 1 : 0;
$pageEnd = min($offset + $perPage, $totalRows);
?>
<?php include __DIR__ . '/includes/header.php'; ?>
<?php include __DIR__ . '/includes/sidebar.php'; ?>
<main class="main sadmin-chapters-main">
    <?php include __DIR__ . '/includes/topbar.php'; ?>
    <section class="content sadmin-chapters-page">
        <section class="card custom-card chapters-hero-card">
            <div class="card-header justify-content-between">
                <div>
                    <span class="text-primary fs-11 fw-semibold text-uppercase d-block mb-1">Course Content</span>
                    <h5 class="mb-1 fw-semibold">Chapters</h5>
                    <p class="mb-0 text-muted fs-12">Global chapter list across instructor courses.</p>
                </div>
            </div>
            <div class="card-body">
                <div class="chapters-mini-stats">
                    <article><span>Total</span><strong><?= h((string) $totalRows); ?></strong></article>
                    <article><span>Published</span><strong><?= h((string) $publishedRows); ?></strong></article>
                    <article><span>Draft / Other</span><strong><?= h((string) $draftRows); ?></strong></article>
                    <article><span>Courses</span><strong><?= h((string) $courseRows); ?></strong></article>
                </div>
            </div>
        </section>

        <section class="card custom-card chapters-register-card">
            <div class="card-header justify-content-between">
                <div>
                    <h6 class="mb-1 fw-semibold">Chapter Register</h6>
                    <p class="mb-0 text-muted fs-12">Showing <?= h((string) $pageStart); ?>-<?= h((string) $pageEnd); ?> of <?= h((string) $totalRows); ?> chapters.</p>
                </div>
                <form class="sadmin-page-size" method="get">
                    <input type="hidden" name="page" value="1">
                    <select class="form-select form-select-sm" name="per_page" onchange="this.form.submit()">
                        <?php foreach ($perPageOptions as $option): ?>
                            <option value="<?= (int) $option; ?>" <?= $perPage === $option ? 'selected' : ''; ?>><?= (int) $option; ?> rows</option>
                        <?php endforeach; ?>
                    </select>
                </form>
            </div>
            <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0 gr-register-table sadmin-chapters-table">
                    <thead>
                    <tr>
                        <th>Course</th>
                        <th>Chapter</th>
                        <th>Type</th>
                        <th>Duration (min)</th>
                        <th>Order</th>
                        <th>Instructor</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php if (!$chapters): ?>
                            <tr><td colspan="7" class="empty-state premium-empty"><strong>No chapter content found</strong><small>Instructor content will appear here after publishing.</small></td></tr>
                        <?php endif; ?>
                        <?php foreach ($chapters as $chapter): ?>
                            <tr>
                                <td><span class="gr-cell-title"><?= h($chapter['course_title']); ?></span><span class="gr-cell-subtitle">Course #<?= (int) $chapter['course_id']; ?></span></td>
                                <td><span class="gr-cell-title"><?= h($chapter['content_title']); ?></span><span class="gr-cell-subtitle">Chapter #<?= (int) $chapter['id']; ?></span></td>
                                <td><span class="badge bg-primary-transparent text-primary"><?= h(ucfirst((string) $chapter['content_type'])); ?></span></td>
                                <td><?= h((string) (int) ($chapter['duration_minutes'] ?? 0)); ?> min</td>
                                <td>#<?= h((string) (int) ($chapter['sort_order'] ?? 0)); ?></td>
                                <td><span class="gr-cell-title"><?= h($chapter['instructor_name'] ?: 'Unassigned'); ?></span></td>
                                <td>
                                    <span class="status-pill <?= ((string) ($chapter['status'] ?? '') === 'published') ? 'ready' : 'empty'; ?>">
                                        <?= h(ucfirst((string) ($chapter['status'] ?? 'draft'))); ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            </div>
            <div class="card-footer sadmin-pagination">
                <span><?= h((string) $pageStart); ?>-<?= h((string) $pageEnd); ?> of <?= h((string) $totalRows); ?> records</span>
                <div>
                    <a class="btn btn-sm btn-light <?= $page <= 1 ? 'disabled' : ''; ?>" href="<?= h(app_url('sadmin/chapters?page=' . max(1, $page - 1) . '&per_page=' . $perPage)); ?>">Prev</a>
                    <span class="page-chip">Page <?= h((string) $page); ?> / <?= h((string) $totalPages); ?></span>
                    <a class="btn btn-sm btn-light <?= $page >= $totalPages ? 'disabled' : ''; ?>" href="<?= h(app_url('sadmin/chapters?page=' . min($totalPages, $page + 1) . '&per_page=' . $perPage)); ?>">Next</a>
                </div>
            </div>
        </section>
    </section>
    <style>
        .sadmin-chapters-main .sadmin-chapters-page { padding-top: 1.25rem; }
        .sadmin-chapters-main .chapters-hero-card,
        .sadmin-chapters-main .chapters-register-card {
            border: 0;
            border-radius: .65rem;
            box-shadow: 0 .85rem 1.85rem rgba(15, 23, 42, .045);
            overflow: hidden;
        }
        .sadmin-chapters-main .chapters-hero-card .card-header,
        .sadmin-chapters-main .chapters-register-card .card-header {
            padding: .75rem 1rem;
            border-bottom: 1px solid var(--default-border);
            background: var(--custom-white);
        }
        .sadmin-chapters-main .chapters-mini-stats {
            display: grid;
            grid-template-columns: repeat(4, minmax(0, 1fr));
            gap: .65rem;
        }
        .sadmin-chapters-main .chapters-mini-stats article {
            display: grid;
            gap: .25rem;
            padding: .65rem .85rem;
            border: 1px solid var(--default-border);
            border-radius: .5rem;
            background: var(--default-background);
        }
        .sadmin-chapters-main .chapters-mini-stats span {
            color: var(--text-muted);
            font-size: .68rem;
            font-weight: 700;
            text-transform: uppercase;
        }
        .sadmin-chapters-main .chapters-mini-stats strong { font-size: 1.1rem; line-height: 1; }
        .sadmin-chapters-main .sadmin-page-size { margin: 0; }
        .sadmin-chapters-main .sadmin-page-size .form-select {
            min-width: 6.8rem;
            min-height: 2rem;
            font-size: .74rem;
        }
        .sadmin-chapters-main .sadmin-chapters-table { min-width: 64rem; }
        .sadmin-chapters-main .sadmin-chapters-table th,
        .sadmin-chapters-main .sadmin-chapters-table td {
            padding: .42rem .65rem !important;
            font-size: .72rem;
            line-height: 1.2;
            vertical-align: middle;
        }
        .sadmin-chapters-main .sadmin-chapters-table th {
            background: var(--default-background);
            font-size: .65rem;
            letter-spacing: .025em;
            text-transform: uppercase;
        }
        .sadmin-chapters-main .sadmin-chapters-table .gr-cell-title {
            display: block;
            max-width: 18rem;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            font-size: .74rem;
            font-weight: 700;
        }
        .sadmin-chapters-main .sadmin-chapters-table .gr-cell-subtitle {
            display: block;
            max-width: 18rem;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            color: var(--text-muted);
            font-size: .66rem;
        }
        .sadmin-chapters-main .sadmin-chapters-table .status-pill,
        .sadmin-chapters-main .sadmin-chapters-table .badge {
            min-height: 1.2rem;
            padding: .15rem .45rem;
            border-radius: 999px;
            font-size: .62rem;
            font-weight: 700;
        }
        .sadmin-chapters-main .sadmin-pagination {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: .75rem;
            padding: .65rem 1rem;
            border-top: 1px solid var(--default-border);
            background: var(--custom-white);
            color: var(--text-muted);
            font-size: .74rem;
        }
        .sadmin-chapters-main .sadmin-pagination > div {
            display: flex;
            align-items: center;
            gap: .35rem;
        }
        .sadmin-chapters-main .sadmin-pagination .btn {
            min-height: 1.55rem;
            padding: .18rem .55rem;
            font-size: .67rem;
        }
        .sadmin-chapters-main .page-chip {
            display: inline-flex;
            align-items: center;
            min-height: 1.55rem;
            padding: .18rem .55rem;
            border-radius: .35rem;
            background: rgba(var(--primary-rgb), .1);
            color: rgb(var(--primary-rgb));
            font-size: .67rem;
            font-weight: 700;
        }
        .sadmin-chapters-main .footer { margin-inline: 0 !important; width: 100%; }
        @media (max-width: 767.98px) {
            .sadmin-chapters-main .chapters-mini-stats { grid-template-columns: repeat(2, minmax(0, 1fr)); }
        }
    </style>
</main>
<?php include __DIR__ . '/includes/footer.php'; ?>

